### ISSUE TITLE
Analysis failed for big typescript project

### ISSUE THREAD

**Issue by jun-jia** [SonarSource/SonarTS#755] opened 2018-09-20 10:50 UTC
**I want to report a bug.**

**SonarTS version:** <1.8><br>
**Node.js version:** <8.11><br>
**typescript version:** <2.4.2><br>
**tslint version:** <5.7.0><br>
**SonarQube version:** <7.2><br>

**Reproducer** 
```
// minimal reproducer if relevant
sonar-scanner -Dsonar.host.url=http://127.0.0.1:9000/ -Dsonar.login=***** -Dsonar.projectKey=tsTest -Dsonar.projectName=tsTest -X -Dsonar.sources=src -Dsonar.language=ts -Dsonar.ts.tslint.configpath=tslint.json -Dsonar.ts.tslint.rulesDir=node_modules/codelyzer -Dsonar.ts.tslint.projectPath=./ -Dsonar.typescript.tslint.reportPaths=issues.json -Dsonar.projectVersion=1.0 -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info -Dsonar.sourceEncoding=UTF-8 -Dsonar.scm.enabled=false
```

**Logs**
```
// logs of analysis if relevant
10:19:28.045 DEBUG: Using Node.js v8.11.3
10:19:28.053 INFO: Analyzing 72 typescript file(s) with the following configuration file /usr/local/Angular-render-engine/tsconfig.json
10:19:28.080 DEBUG: Setting 'NODE_PATH' to /usr/local/Angular-render-engine/node_modules
10:19:28.081 DEBUG: Starting external process `node --max-old-space-size=6144 /usr/local/Angular-render-engine/.scannerwork/sonarts-bundle/node_modules/tslint-sonarts/bin/tsrunner`
10:40:38.339 ERROR: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
10:40:38.341 ERROR:  1: node::Abort() [node]
10:40:38.343 ERROR:  2: 0x8c21ec [node]
10:40:38.343 ERROR:  3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
10:40:38.344 ERROR:  4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
10:40:38.345 ERROR:  5: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
10:40:38.345 ERROR:  6: 0xd4ad73 [node]
10:40:38.346 ERROR:  7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node]
10:40:38.346 ERROR:  8: 0x31bd9c042fd
10:41:01.922 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 7,351ms last 8 cycles average is 918ms
10:42:52.026 INFO: ------------------------------------------------------------------------
10:42:52.026 INFO: EXECUTION FAILURE
10:42:52.026 INFO: ------------------------------------------------------------------------
10:42:52.027 INFO: Total time: 23:30.667s
10:42:52.975 INFO: Final Memory: 13M/333M
10:42:52.976 INFO: ------------------------------------------------------------------------
10:42:52.976 ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Failed to run external process `node --max-old-space-size=6144 /usr/local/Angular-render-engine/.scannerwork/sonarts-bundle/node_modules/tslint-sonarts/bin/tsrunner`. Run with -X for more information
        at org.sonar.plugin.typescript.ExternalTypescriptSensor.executeExternalRunner(ExternalTypescriptSensor.java:256)
        at org.sonar.plugin.typescript.ExternalTypescriptSensor.analyze(ExternalTypescriptSensor.java:130)
        at org.sonar.plugin.typescript.ExternalTypescriptSensor.execute(ExternalTypescriptSensor.java:111)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:312)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:307)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:281)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:81)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:132)
        at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 2 column 1 path $
        at com.google.gson.Gson.fromJson(Gson.java:891)
        at com.google.gson.Gson.fromJson(Gson.java:817)
        at org.sonar.plugin.typescript.ExternalTypescriptSensor.executeExternalRunner(ExternalTypescriptSensor.java:247)
        ... 34 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 2 column 1 path $
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:351)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
        at com.google.gson.Gson.fromJson(Gson.java:879)
        ... 36 more

```

**Expected behavior**

**I want to provide the following feedback.**
It was working fine last month, but failed with heap out of memory recently. We've 10GB memory available when running scanner.

The --max-old-space-size was set to 2048 in SonarTS1.8, I tried to downloaded the source code of SonarTS and updated the size to 4096, then 6144, but it still report heap out of memory.

**Rule key:** 

**Example**

**Comment by DanielRuf** [comment] 2019-01-13 19:45
Is there a workaround to increase the limit or disable this check?

**Comment by RaghuHoskote** [comment] 2019-06-11 09:17
@DanielRuf  ran in to same issue, how do we fix this :)

**Comment by bhanush3** [comment] 2019-08-13 12:57
I have faced this issue while running SonarQube in Azure WebApp for Containers

**Comment by Alver23** [comment] 2019-08-21 15:35
Hi, is it possible to configure max_old_space_size when executing sonar analysis?

**Comment by salifukayta** [comment] 2020-04-16 12:34
I'm in the same situation. But we get the erreur only when jenkins job is scanning the project. We have jenkins on unix in docker. I don't reproduce locally on windows.
Any news ?

**Comment by vilchik-elena** [comment] 2020-05-18 13:43
Closing this issue as SonarTS is deprecated. Please use SonarJS to analyze TS code (since sonarjs 6.0), and if problem persists, report in https://community.sonarsource.com/

**Closed by vilchik-elena** 2020-05-18 13:43 UTC
Labels: bug
