### ISSUE TITLE
Wrong order of tokens when calculating syntax highlighting

### ISSUE THREAD

**Issue by jvanoostveen** [SonarSource/SonarTS#204] opened 2017-09-20 12:49 UTC
When running the scanner, I get the following error (paths changed for clearity).
```
14:39:20.949 ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Tokens of file [moduleKey=a:b, relative=src/a/dynamic-page-loader.ts, basedir=C:\a] should be provided in order.
Previous token: Range[from [line=51, lineOffset=12] to [line=51, lineOffset=22]]
Last token: Range[from [line=49, lineOffset=12] to [line=49, lineOffset=20]]
```

When I look at the code mentioned, it is a type cast (example code reflects the actual code):
```
  /**
   * @param a
   * @param b
   */
(window as any).someSpecialFunction = () => '...';
```

When I remove the comment/documentation above it, the scanner will work, but the server will report an error:
```
2017.09.20 12:34:02 WARN  ce[AV6fR7Qet3D091CMKW_3][o.s.s.c.t.p.s.HighlightingLineReader] Inconsistency detected in Highlighting data. Highlighting will be ignored for file 'a:b:src/a/dynamic-page-loader.ts'
org.sonar.server.computation.task.projectanalysis.source.RangeOffsetConverter$RangeOffsetConverterException: Start offset 10 is defined outside the length (5) of the line 48
        at org.sonar.server.computation.task.projectanalysis.source.RangeOffsetConverter.checkExpression(RangeOffsetConverter.java:65)
        at org.sonar.server.computation.task.projectanalysis.source.RangeOffsetConverter.validateStartOffsetNotGreaterThanLineLength(RangeOffsetConverter.java:54)
        at org.sonar.server.computation.task.projectanalysis.source.RangeOffsetConverter.offsetToString(RangeOffsetConverter.java:33)
        at org.sonar.server.computation.task.projectanalysis.source.HighlightingLineReader.processHighlighting(HighlightingLineReader.java:104)
        at org.sonar.server.computation.task.projectanalysis.source.HighlightingLineReader.processHighlightings(HighlightingLineReader.java:91)
        at org.sonar.server.computation.task.projectanalysis.source.HighlightingLineReader.read(HighlightingLineReader.java:78)
        at org.sonar.server.computation.task.projectanalysis.source.ComputeFileSourceData.read(ComputeFileSourceData.java:61)
        at org.sonar.server.computation.task.projectanalysis.source.ComputeFileSourceData.compute(ComputeFileSourceData.java:48)
        at org.sonar.server.computation.task.projectanalysis.step.PersistFileSourcesStep$FileSourceVisitor.visitFile(PersistFileSourcesStep.java:121)
        at org.sonar.server.computation.task.projectanalysis.component.DepthTraversalTypeAwareCrawler.visitNode(DepthTraversalTypeAwareCrawler.java:79)
        at org.sonar.server.computation.task.projectanalysis.component.DepthTraversalTypeAwareCrawler.visitImpl(DepthTraversalTypeAwareCrawler.java:51)
        at org.sonar.server.computation.task.projectanalysis.component.DepthTraversalTypeAwareCrawler.visit(DepthTraversalTypeAwareCrawler.java:39)
        at org.sonar.server.computation.task.projectanalysis.component.DepthTraversalTypeAwareCrawler.visitChildren(DepthTraversalTypeAwareCrawler.java:98)
        at org.sonar.server.computation.task.projectanalysis.component.DepthTraversalTypeAwareCrawler.visitImpl(DepthTraversalTypeAwareCrawler.java:54)
        at org.sonar.server.computation.task.projectanalysis.component.DepthTraversalTypeAwareCrawler.visit(DepthTraversalTypeAwareCrawler.java:39)
        at org.sonar.server.computation.task.projectanalysis.component.DepthTraversalTypeAwareCrawler.visitChildren(DepthTraversalTypeAwareCrawler.java:98)
        at org.sonar.server.computation.task.projectanalysis.component.DepthTraversalTypeAwareCrawler.visitImpl(DepthTraversalTypeAwareCrawler.java:54)
        at org.sonar.server.computation.task.projectanalysis.component.DepthTraversalTypeAwareCrawler.visit(DepthTraversalTypeAwareCrawler.java:39)
        at org.sonar.server.computation.task.projectanalysis.component.DepthTraversalTypeAwareCrawler.visitChildren(DepthTraversalTypeAwareCrawler.java:98)
        at org.sonar.server.computation.task.projectanalysis.component.DepthTraversalTypeAwareCrawler.visitImpl(DepthTraversalTypeAwareCrawler.java:54)
        at org.sonar.server.computation.task.projectanalysis.component.DepthTraversalTypeAwareCrawler.visit(DepthTraversalTypeAwareCrawler.java:39)
        at org.sonar.server.computation.task.projectanalysis.step.PersistFileSourcesStep.execute(PersistFileSourcesStep.java:89)
        at org.sonar.server.computation.task.step.ComputationStepExecutor.executeSteps(ComputationStepExecutor.java:64)
        at org.sonar.server.computation.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:52)
        at org.sonar.server.computation.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:75)
        at org.sonar.ce.taskprocessor.CeWorkerImpl.executeTask(CeWorkerImpl.java:92)
        at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:59)
        at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:35)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

When I rewrite this line to make it not start with `(window as any)`, it will work in the Scanner and on the server (even with the comment above it).

Environment:
OS: Windows 10
Shell: PowerShell
Scanner: 3.0.3.778
SonarQube: 6.5.0 (alpine latest)
TypeScript: 2.5.2

**Comment by vilchik-elena** [comment] 2017-09-21 07:22
@jvanoostveen thanks for the bug! We will fix it in next version

**Comment by vilchik-elena** [comment] 2017-10-04 14:04
hi @jvanoostveen, unfortunately I can't reproduce the problem with the code sample you provided. For me highlighting of it works perfectly fine. Probably some context matters. Could you show me a bigger sample failing analysis? thanks!

**Comment by Kajvdh** [comment] 2017-10-18 05:16
I got the same problem. it crashes on this line (the second line):

```
/**
* @param {() => KlantenLijst} klantenLijstSupplier. Supplier, for use in a reactive environment.
*/
```

This was the stacktrace:

```
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Tokens of file [moduleKey=project-web, relative=src/validator.ts, basedir=/Users/Kaj/Git/project] should be provided in order.
Previous token: Range[from [line=8, lineOffset=16] to [line=8, lineOffset=17]]
Last token: Range[from [line=8, lineOffset=14] to [line=8, lineOffset=15]]
	at org.sonar.api.internal.google.common.base.Preconditions.checkState(Preconditions.java:197)
	at org.sonar.api.batch.sensor.cpd.internal.DefaultCpdTokens.addToken(DefaultCpdTokens.java:91)
	at org.sonar.api.batch.sensor.cpd.internal.DefaultCpdTokens.addToken(DefaultCpdTokens.java:80)
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.saveCpd(ExternalTypescriptSensor.java:251)
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.runMetrics(ExternalTypescriptSensor.java:168)
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.execute(ExternalTypescriptSensor.java:107)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:179)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:261)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:256)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:245)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:119)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
child_process.js:495
    throw err;
    ^
```

**Comment by vilchik-elena** [comment] 2017-10-18 07:07
@Kajvdh Thanks for reporting! Could you provide bigger code sample? with only this comment I can't reproduce

**Comment by nagasainatht** [comment] 2018-02-05 16:31
Today I able to get the same problem like below:

Tokens of file src/main/js/src/checkboxGroup/DetailedViewCheckboxGroup.tsx should be provided in order.

**Comment by nagasainatht** [comment] 2018-02-05 16:31
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar (default-cli) on project legato-blotter: Tokens of file src/main/js/src/checkboxGroup/DetailedViewCheckboxGroup.tsx should be provided in order.
[ERROR] Previous token: Range[from [line=28, lineOffset=12] to [line=28, lineOffset=13]]
[ERROR] Last token: Range[from [line=28, lineOffset=12] to [line=28, lineOffset=13]]

**Comment by nagasainatht** [comment] 2018-02-05 16:35
Today I got the same problem with latest SonarQube. Please find the below error details:

Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar (default-cli) on project legato-blotter: Tokens of file src/main/js/src/checkboxGroup/CheckboxGroup.tsx should be provided in order.
[ERROR] Previous token: Range[from [line=25, lineOffset=11] to [line=25, lineOffset=12]]
[ERROR] Last token: Range[from [line=25, lineOffset=11] to [line=25, lineOffset=12]]

And lines of code starts from 25 are:

 <div className={getClassName(this.props, classNames('row', style.root))}>
           <div className={style.label}>{this.props.label}</div>
           <div className={classNames('row', style.checkboxContainer)}>
              {this.renderCheckboxes(this.props.setFilterSelections)}
            </div>
         </div>

Could you please let me know what is the problem and how to resolve this issue

**Comment by vilchik-elena** [comment] 2018-02-05 16:44
@nagasainatht could you provide entire file? (you can minify it if it doesn't break the reproducibility)

**Comment by nagasainatht** [comment] 2018-02-06 13:06
I tried to comment few files which produced this issues.But for all .jsx files I am able to see issue reported at render method which has html elements started.
May I know what are the expectations during this scanning from .jsx files and logic is in 

sonarqube/sonar-plugin-api/src/main/java/org/sonar/api/batch/sensor/cpd/internal/DefaultCpdTokens.java file

Sorry as per company policty I can't share the code.

**Comment by nagasainatht** [comment] 2018-02-06 13:07
you can find the below code for sample where I am able to see issue

ReactDom.render(
   <AppShell app={appDescriptor}>
      <div className={style.root}>
         <BlotterContainer
            className={style.blotterContainer}
            predicates={parsedPredicates}
         />
      </div>
   </AppShell>,
   document.getElementById('root')

**Comment by nagasainatht** [comment] 2018-02-06 13:08
ReactDom.render(
   "<AppShell app={appDescriptor}>
      <div className={style.root}>
         <BlotterContainer
            className={style.blotterContainer}
            predicates={parsedPredicates}
         />
      </div>
   </AppShell>,"
   document.getElementById('root')

**Comment by nagasainatht** [comment] 2018-02-06 13:09
ReactDom.render(
   /**<AppShell app={appDescriptor}>
      <div className={style.root}>
         <BlotterContainer
            className={style.blotterContainer}
            predicates={parsedPredicates}
         />
      </div>
   </AppShell>,**/
   document.getElementById('root')

**Comment by nagasainatht** [comment] 2018-02-06 13:10
You can find the sample code below:

**Comment by vilchik-elena** [comment] 2018-08-28 15:37
Closing as we failed to reproduce problem

**Closed by vilchik-elena** 2018-08-28 15:37 UTC
Labels: bug
