### ISSUE TITLE
Analysis fails on TFS

### ISSUE THREAD

**Issue by olsh** [SonarSource/SonarTS#190] opened 2017-08-23 20:47 UTC
We are using [TFS Extension](https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Extension+for+VSTS-TFS) and SonarQube server with SonarTS plugin installed.

When TFS executes `Complete the SonarQube analysis` step, the following error is printed in TFS console.

```
INFO: Sensor TypeScript Sensor
INFO: Metrics calculation
ERROR: Failed to run external process `node F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod60\sonarts-core\node_modules\tslint-sonarts\bin\tsmetrics`. As a result, NO METRICS WERE GENERATED, run with -X for more information
java.io.IOException: The pipe has been ended
at java.io.FileOutputStream.writeBytes(Native Method) ~[na:1.8.0_111]
at java.io.FileOutputStream.write(FileOutputStream.java:326) ~[na:1.8.0_111]
at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122) ~[na:1.8.0_111]
at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[na:1.8.0_111]
at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282) ~[na:1.8.0_111]
at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125) ~[na:1.8.0_111]
at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:135) ~[na:1.8.0_111]
at java.io.OutputStreamWriter.write(OutputStreamWriter.java:220) ~[na:1.8.0_111]
at java.io.Writer.write(Writer.java:157) ~[na:1.8.0_111]
at org.sonar.plugin.typescript.ExternalTypescriptSensor.runMetricsProcess(ExternalTypescriptSensor.java:190) [sonar-typescript-plugin-1.0.0.340.jar:na]
at org.sonar.plugin.typescript.ExternalTypescriptSensor.runMetrics(ExternalTypescriptSensor.java:160) [sonar-typescript-plugin-1.0.0.340.jar:na]
at org.sonar.plugin.typescript.ExternalTypescriptSensor.execute(ExternalTypescriptSensor.java:107) [sonar-typescript-plugin-1.0.0.340.jar:na]
at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119) [sonar-scanner-engine-shaded-5.6.6.jar:na]
at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63) [sonar-scanner-api-batch6100729998043800075.jar:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
INFO: Rules execution
at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60) [sonar-scanner-cli-3.0.3.778.jar:na]
at com.sun.proxy.$Proxy0.execute(Unknown Source) [na:na]
at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233) [sonar-scanner-cli-3.0.3.778.jar:na]
at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151) [sonar-scanner-cli-3.0.3.778.jar:na]
at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123) [sonar-scanner-cli-3.0.3.778.jar:na]
at org.sonarsource.scanner.cli.Main.execute(Main.java:77) [sonar-scanner-cli-3.0.3.778.jar:na]
at org.sonarsource.scanner.cli.Main.main(Main.java:61) [sonar-scanner-cli-3.0.3.778.jar:na]
```

When I try to execute the suggested command
`node F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod60\sonarts-core\node_modules\tslint-sonarts\bin\tsmetrics -X` I get the follwing:

```
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod60\sonarts-core\node_modules\tslint-sonarts\l
ib\runner\tsmetrics.js:23:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Typescript is installed globally on the machine.

## Configuration

TFS 2017 RTM
SonarQube 5.6 LTS
SonarQube Extension for VSTS/TFS 3.0.2
SonarTS 1.0.0.340

**Comment by inverno** [comment] 2017-08-24 08:52
@ols thanks a lot for that last line, it makes the answer very straightforward :
SonarTS uses Typescript as a library, it `require`s it. When you install a package globally you will only be able to use it as command-line tool (for Typescript this is typically to run `tsc`), but code analyzers such as SonarTS don't use Typescript as a tool. Instead we need to use the abstract syntax tree that is defined in the Typescript library and plenty of other things which are not related to command-line scripts.
For that, you need to have typescript as a project dependency or (but this is discouraged by node.js documentation) to set the `NODE_PATH` variable as described in the approved answer to [this SO](https://stackoverflow.com/questions/15636367/nodejs-require-a-global-module-package).

I think we should document this, as you are certainly not alone in using Typescript only as a command-line tool and even if there seems to be a tendency to declare more and more tools as part of project dependencies instead of going global, it's by no means universal.

**Comment by olsh** [comment] 2017-08-24 10:13
Hi, @inverno thanks for the reply!

We have typescript as a dependency in the projects. And we restore the dependencies before the analysis.

Probably there is some issue with directories?

```
2017-08-24T09:40:30.7472251Z INFO: -------------  Scan Project.Name
2017-08-24T09:40:30.7472251Z INFO: Base dir: F:\TFS\Agentv2\_work\2\s\src\Project.Name
2017-08-24T09:40:30.7472251Z INFO: Working dir: F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod59
2017-08-24T09:40:30.8566573Z INFO: Source encoding: UTF-8, default locale: en_US
2017-08-24T09:40:30.8566573Z INFO: Index files
2017-08-24T09:40:30.8566573Z INFO: Analyzer working directory contains 5 .pb file(s)
2017-08-24T09:40:31.1847808Z INFO: 230 files indexed
2017-08-24T09:40:31.1847808Z INFO: Quality profile for cs: Sonar way
2017-08-24T09:40:31.1847808Z INFO: Quality profile for ts: Sonar way
2017-08-24T09:40:31.1847808Z INFO: Sensor Lines Sensor
2017-08-24T09:40:31.1847808Z INFO: Sensor Lines Sensor (done) | time=0ms
2017-08-24T09:40:31.1847808Z INFO: Sensor SCM Sensor
2017-08-24T09:40:31.1847808Z INFO: SCM provider for this project is: git
2017-08-24T09:40:31.1847808Z INFO: 184 files to be analyzed
2017-08-24T09:40:40.1377904Z INFO: 183/184 files analyzed
2017-08-24T09:40:40.1377904Z INFO: Sensor SCM Sensor (done) | time=9000ms
2017-08-24T09:40:40.1377904Z INFO: Sensor C#
2017-08-24T09:40:40.1377904Z INFO: Importing analysis results from F:\TFS\Agentv2\_work\2\.sonarqube\out\Project.Name_8271\output-cs
2017-08-24T09:40:40.1377904Z WARNING: WARN: Missing blame information for the following files:
2017-08-24T09:40:40.1377904Z WARNING: WARN:   * F:/TFS/Agentv2/_work/2/s/src/Project.Name/obj/Debug/net461/Project.Name.AssemblyInfo.cs
2017-08-24T09:40:40.1377904Z WARNING: WARN: This may lead to missing/broken features in SonarQube
2017-08-24T09:40:40.1377904Z INFO: Importing Roslyn report
2017-08-24T09:40:40.2473003Z INFO: Sensor C# (done) | time=47ms
2017-08-24T09:40:40.2473003Z INFO: Sensor C# Unit Tests Coverage Report Import
2017-08-24T09:40:40.2473003Z INFO: Sensor C# Unit Tests Coverage Report Import (done) | time=0ms
2017-08-24T09:40:40.2473003Z INFO: Sensor C# Integration Tests Coverage Report Import
2017-08-24T09:40:40.2473003Z INFO: Sensor C# Integration Tests Coverage Report Import (done) | time=0ms
2017-08-24T09:40:40.2473003Z INFO: Sensor C# Unit Test Results Import
2017-08-24T09:40:40.2473003Z INFO: Sensor C# Unit Test Results Import (done) | time=0ms
2017-08-24T09:40:40.2473003Z INFO: Sensor TypeScript Sensor
2017-08-24T09:40:41.3409077Z INFO: Metrics calculation
2017-08-24T09:40:41.7784499Z ##[error]ERROR: Failed to run external process `node F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod59\sonarts-core\node_modules\tslint-sonarts\bin\tsmetrics`. As a result, NO METRICS WERE GENERATED, run with -X for more information
```

We have `node_modules` with typescript dependency in this folder `F:\TFS\Agentv2\_work\2\s\src\Project.Name` but the scanner starts SonarTS from this one `F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod59\sonarts-core\node_modules\tslint-sonarts\bin\tsmetrics`.

Can this be a problem?

**Comment by olsh** [comment] 2017-08-24 11:44
Well, I managed to solve the issue with running the following command before analysis:
`yarn install --modules-folder $(Agent.BuildDirectory)\node_modules`

In this way, the `node_modules` will be in the folder `F:\TFS\Agentv2\_work\2` and everything works fine.
But it looks like a workaround.

**Comment by inverno** [comment] 2017-08-24 14:11
@olsh it is indeed a workaround.
In general we expected that the work directory (what you have in your log mentioned as `Working dir: F:\TFS\Agentv2\_work\2\.sonarqube...`) would almost always be a sub-folder of the target project.
The reason why I did not answer at once is that we are investigating if this is not corner case specific to your setup, but a general case when using TFS.
I'll update this issue when I find out and, if it's a general case, we'll see what we can do. If it's specific to your set-up I might be able to point you to the configuration required to have the work directory inside your project folder.

**Comment by inverno** [comment] 2017-08-29 11:58
Hi @olsh sorry if it took me a bit of time. The TFS integration is setting up the default work dir in a way that we had not accounted for.

Your work-around is as good or better than any other thing I might suggest. I'll close this thread and reference it from a new issue that I'll add to our next release: we have an idea or two on how to make this mechanic work seamlessly with TFS.

Thanks for your feedback and depth in providing information on this topic. I hope that, after the initial problem, SonarTS is proving useful to you :)

**Closed by inverno** 2017-08-29 11:58 UTC

**Comment by davidreher** [comment] 2017-09-26 14:19
I have the same issue as @olsh. What I did to fix it:
1. add a new npm build step
2. set *Command* to `custom`
3. set *Working folder with package.json* to `$(Agent.BuildDirectory)`
4. set *Command and arguments* to `install typescript@2.3.3`

**Comment by psurani** [comment] 2018-01-03 19:28
Hello, I tried above, but got below error message:
ERROR: External process failed with empty output: `node 
Please help

**Comment by vilchik-elena** [comment] 2018-01-04 08:24
@psurani do you reproduce the problem with latest release 1.3.0?

**Comment by psurani** [comment] 2018-01-04 17:29
Hi @vilchik-elena , 

I am on SonarQube version 5.6.7 which doesn't support Typescript plugin 1.3.0. So I am having version 1.0.1
Below is the log:
INFO: Quality profile for ts: TsLint
INFO: JaCoCoSensor: JaCoCo report not found : C:\Users\**\workspace\target\jacoco.exec
INFO: JaCoCoItSensor: JaCoCo IT report not found: C:\Users\**\workspace\target\jacoco-it.exec
INFO: Sensor Lines Sensor
INFO: Sensor Lines Sensor (done) | time=131ms
INFO: Sensor SCM Sensor
INFO: SCM Publisher is disabled
INFO: Sensor SCM Sensor (done) | time=0ms
INFO: Sensor TypeScript Sensor
INFO: Metrics calculation
INFO: Rules execution
INFO: Running rule analysis for `C:\Users\**\workspace\tsconfig.json` with 63 files
INFO: Sensor TypeScript Sensor (done) | time=16203ms
INFO: Sensor TypeScript LCOV Coverage Sensor
INFO: Sensor TypeScript LCOV Coverage Sensor (done) | time=0ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=147ms
INFO: Sensor Code Colorizer Sensor
INFO: Sensor Code Colorizer Sensor (done) | time=3ms
INFO: Sensor CPD Block Indexer
INFO: DefaultCpdBlockIndexer is used for ts
INFO: Sensor CPD Block Indexer (done) | time=0ms
INFO: Calculating CPD for 49 files
INFO: CPD calculation finished


Firstly I dont know why it is referring to tsconfig.json, while i have set tslint.json as my config file
Below is the analysis properties:
sonar.host.url=http://localhost:9000
sonar.jdbc.url=jdbc:h2:tcp://127.0.0.1:9092/sonar
sonar.jdbc.username=
sonar.jdbc.password=
sonar.sourceEncoding=UTF-8
sonar.projectBaseDir=.
sonar.projectKey=MyProject_Key
sonar.projectName=MyProject_Name
sonar.projectVersion=1.0
sonar.scm.provider=svn
sonar.scm.disabled=true
sonar.language=ts
sonar.ts.analyzer.projectOutPaths=./TsLint_PTS_Out
sonar.ts.tslint.path=./node_modules/tslint/bin
sonar.ts.tslint.configPath=./tslint.json
sonar.sources=.
sonar.report.export.path=.
set SONAR_RUNNER_OPTS=-Xmx512m -XX:MaxPermSize=128m -XX:-UseGCOverheadLimit 
sonar.exclusions=spec.ts, node_modules/**

Any help appreciated

**Comment by vilchik-elena** [comment] 2018-01-05 08:21
Ah, you probably want to use another plugin https://github.com/Pablissimo/SonarTsPlugin, but SonarTS fails. Try to uninstall it

**Comment by psurani** [comment] 2018-01-05 11:08
Hi @vilchik-elena, thanks for your response.
I figured out that there were three profiles under TypeScript in SonarQube
They were:
SonarWay (28 rules)
Sonarway Recommended (58 rules)
TsLint (0 rules)

And i could see that TsLint was the default. So i selected SonarWay Recommended as the default and it did some trick as I could see some figures in Code Smell section!

However Can you please let me know what is the purpose of package.json in a project folder?
Is it every referred during Sonar Analysis?

**Comment by vilchik-elena** [comment] 2018-01-08 10:31
> However Can you please let me know what is the purpose of package.json in a project folder?
Is it every referred during Sonar Analysis?

What do you mean? which project folder? 
SonarTS doesn't require `package.json`, while it requires `node_modules` with `typescript` dependency inside and tsconfig.json
