### ISSUE TITLE
SonarTS throws exceptions and fails analysis when starting analysis on large number of files

### ISSUE THREAD

**Issue by larsflagan** [SonarSource/SonarTS#252] opened 2017-10-25 10:17 UTC
SonarTS throws exceptions when starting analysis on large number of files when running from MSBuild Scanner and also Sonar Scanner.   
 
java.lang.IllegalStateException: Failed to run external process `node C:\projects\.scannerwork\sonarts-core\node_modules\tslint\bin\tslint --config C:\projects\project\.scannerwork\sonarts-core\tslint.json --format json --force --type-check --project C:\projects\project\src\projectfolder\tsconfig.json ... references to lots of .ts files ....
    at org.sonar.plugin.typescript.ExternalTypescriptSensor.runRulesProcess(ExternalTypescriptSensor.java:243)
    at org.sonar.plugin.typescript.ExternalTypescriptSensor.runRules(ExternalTypescriptSensor.java:126)
    at org.sonar.plugin.typescript.ExternalTypescriptSensor.execute(ExternalTypescriptSensor.java:113)
    at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
    at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
    at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
    at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
    at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
    at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
    at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:286)
    at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:281)
    at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:279)
    at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:259)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
    at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
    at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
    at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
    at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:118)
    at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:113)
    at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
    at com.sun.proxy.$Proxy0.execute(Unknown Source)
    at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
    at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
    at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
    at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
    at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.io.IOException: Cannot run program "node": CreateProcess error=206, The filename or extension is too long
    at java.lang.ProcessBuilder.start(Unknown Source)
    at org.sonar.plugin.typescript.ExternalTypescriptSensor.runRulesProcess(ExternalTypescriptSensor.java:218)
    ... 35 more
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
    at java.lang.ProcessImpl.create(Native Method)
    at java.lang.ProcessImpl.<init>(Unknown Source)
    at java.lang.ProcessImpl.start(Unknown Source)
    ... 37 more

Is there a workaround or perhaps a way to make it fail more gracefully so that the entire analysis including other languages does not fail?

**Comment by inverno** [comment] 2017-10-25 12:39
Duplicate of #193
@larsflagan this is fixed in 1.1.0, currently in RC, I suggest you try it, otherwise you can wait tomorrow for the release of 1.1.0

**Closed by inverno** 2017-10-25 12:39 UTC

**Comment by larsflagan** [comment] 2017-10-25 12:41
Thanks for the quick response! Will try out the RC tonight.
